version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:7.14.1
    container_name: elasticsearchDb
    restart: unless-stopped
    volumes:
    - /opt/data:/data/db
    ports:
    - 9200:9200
    - 9300:9300
    environment:
    - discovery.type=single-node
